apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogIlFteDVZV0owY205cE9tZG9jRjlYY1U5a1ZrWmFTakJxTWxCa05VWnNWWEJzY0VaUWVrbFRTMlpHZEVreFJHcEpiWGM9IiwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0K
type: kubernetes.io/dockerconfigjson
