apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson:ewogICAgImF1dGhzIjogImdoY3IuaW8iOiB7CiAgICAgICAgImVtYWlsIjogImJseWFidHJvaUBnbWFpbC5jb20iLAogICAgICAgICJhdXRoIjogIllteDVZV0owY205cE9tZG9jRjlEVW5odmJHRkhUMVJQTlhCeFJUZGlSRkZ1VW1OU2QwVjBRMFpGYkhZd1YxUXpObVU9IgogICAgICB9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQo=
type: kubernetes.io/dockerconfigjson
