apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogImdoY3IuaW8iOiB7CiAgICAgICAgImVtYWlsIjogImJseWFidHJvaUBnbWFpbC5jb20iLAogICAgICAgICJhdXRoIjogIlFteDVZV0owY205cE9tZG9jRjlYY1U5a1ZrWmFTakJxTWxCa05VWnNWWEJzY0VaUWVrbFRTMlpHZEVreFJHcEpiWGM9IgogICAgICB9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQo=
type: kubernetes.io/dockerconfigjson
