@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь", "Использует CinemaAbyss API")
Person(admin, "Администратор", "Мониторит события через Kafka UI")

System_Boundary(s1, "CinemaAbyss") {
  Container(proxy, "Proxy Service (API Gateway)", "Go", "Маршрутизация запросов к сервисам")
  Container(monolith, "Monolith Service", "Go", "Обрабатывает пользователей, платежи, подписки, CRUD")
  Container(movies, "Movies Microservice", "Go", "CRUD")
  Container(events, "Events Microservice", "Go", "Работа с событиями пользователей и фильмов")
  ContainerDb(db, "PostgreSQL", "Реляционная БД", "Хранение данных")
  Container(kafka, "Kafka", "Kafka", "Брокер событий")
  Container(zoo, "ZooKeeper", "ZooKeeper", "Координация Kafka-кластера")
  Container(kafkaui, "Kafka UI", "Web UI", "Мониторинг событий и топиков Kafka")
}

Rel(user, proxy, "Запрос", "HTTP")
Rel(admin, kafkaui, "Запрос", "HTTP")

Rel(proxy, monolith, "Запросы", "HTTP")
Rel(proxy, movies, "Запросы", "HTTP")
Rel(proxy, events, "Запросы", "HTTP")

Rel(monolith, db, "SQL - запросы")
Rel(movies, db, "SQL - запросы")
Rel(events, db, "SQL - запросы")

Rel(events, kafka, "Пишет/читает события")
Rel(kafka, zoo, "Координация")
Rel_U(kafkaui, kafka, "Мониторинг топиков", "Kafka API")
Rel_U(kafkaui, zoo, "Статус брокеров", "ZooKeeper API")

@enduml
